[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn brain_tumor_detector.wsgi:application"
